### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by LenisLin** [dakomura/histo_patch#1]
Hi @dakomura @rannyrh, thank you for developing such an impressive method! Unfortunately, I've been having some difficulty with installation through pip due to package conflicts. Would it be possible for you to package it into a Conda environment or a Docker container? This would make the application process much more straightforward for me. Thanks in advance!

**Comment by dakomura** [comment]
Hi @Lin-Yux ,

Thank you for your interest!

The docker image for histo_patch can be found at https://hub.docker.com/r/dkomura/histopatch. 
Please give it a try.
If you have any questions or need further assistance, don't hesitate to ask.

**Comment by LenisLin** [comment]
Thank you for your prompt response! I'll give it a try right away. Wishing you all the best!

**Comment by LenisLin** [comment]
Hi, I've encountered an error stating, 
```{bash}
"Unable to find image 'histopatch:latest' locally. 
Docker: Error response from daemon: pull access denied for histopatch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied." 
```
This is puzzling to me because I have indeed pulled the Docker image locally, and I can see it listed when I run the "docker images" command. Could you help me understand what might be causing this issue? Thank you!

**Comment by dakomura** [comment]
I'm sorry to bother you.
I have noticed that the usage shown in Docker Hub was wrong.

Please try
```
docker run --rm -v /data:/data dkomura/histopatch histopatch /data/wsi/wsifile /data/output 
```

**Comment by LenisLin** [comment]
I apologize for troubling you again, but I've encountered an issue while running the following command:
```{bash}
docker run --rm -v /data:/data dkomura/histopatch /data/wsi/wsifile /data/output
```

It's resulting in this error:

```{bash}
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/data/wsi/wsifile\": stat /data/wsi/wsifile: no such file or directory": unknown.
```

It appears the issue might be related to the directory path not existing. Could you possibly assist me in resolving this? Thank you!

**Comment by dakomura** [comment]
I'm sorry for the confusion again.

To correctly use the tool, run:
```
docker run -v [YOUR_DATA_DIRECTORY]:/data --rm dkomura/histopatch histopatch /data/PATH_TO_WSI /data/PATH_TO_SAVE_DIRECTORY

```
Note that
1. Ensure you mount your data directory using the `-v` option.
2. Replace PATH_TO_WSI with the path to your Whole Slide Image.
3. Replace PATH_TO_SAVE_DIRECTORY with the desired output directory.

For the options, please run
```
docker run --rm dkomura/histopatch histopatch --help
```

If you need further assistance, don't hesitate to ask!
